In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
independent=dataset[['age', 'bmi', 'children', 'sex_male','smoker_yes']]
dependent=dataset[['charges']]

In [7]:
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
param_grid={'kernel':['rbf','poly','sigmoid','linear'],
           'C':[10,100,1000,2000,3000]}
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [8]:
re=grid.cv_results_
print("The R Score value for the best Parameter{}:".format(grid.best_params_))

The R Score value for the best Parameter{'C': 1000, 'kernel': 'linear'}:

In [9]:
table=pd.DataFrame.from_dict(re)

In [10]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.198461,0.391696,0.315006,0.012246,10,rbf,"{'C': 10, 'kernel': 'rbf'}",-0.110409,-0.097459,-0.074488,-0.099597,-0.124428,-0.101276,0.016459,9
1,0.789313,0.097579,0.119327,0.048815,10,poly,"{'C': 10, 'kernel': 'poly'}",-0.125153,-0.081505,-0.111907,-0.131602,-0.179328,-0.125899,0.031794,12
2,0.902244,0.024597,0.283626,0.014584,10,sigmoid,"{'C': 10, 'kernel': 'sigmoid'}",-0.116743,-0.119312,-0.085214,-0.108210,-0.108716,-0.107639,0.012029,10
3,3.422291,4.270611,0.094942,0.058308,10,linear,"{'C': 10, 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,6
4,0.814698,0.007273,0.297617,0.004704,100,rbf,"{'C': 100, 'kernel': 'rbf'}",-0.160182,-0.107253,-0.123430,-0.137753,-0.209551,-0.147634,0.035511,17
5,0.773523,0.035181,0.044372,0.039778,100,poly,"{'C': 100, 'kernel': 'poly'}",-0.132885,-0.082461,-0.129220,-0.139962,-0.189219,-0.134749,0.033948,14
6,0.831687,0.002637,0.264038,0.001938,100,sigmoid,"{'C': 100, 'kernel': 'sigmoid'}",-0.142455,-0.160831,-0.117544,-0.137984,-0.130402,-0.137843,0.014263,15
7,1.509548,0.086159,0.081351,0.067896,100,linear,"{'C': 100, 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,4
8,0.969543,0.047950,0.393758,0.068879,1000,rbf,"{'C': 1000, 'kernel': 'rbf'}",-0.155430,-0.098267,-0.123724,-0.137137,-0.206405,-0.144193,0.036262,16
9,1.049152,0.016069,0.108333,0.067698,1000,poly,"{'C': 1000, 'kernel': 'poly'}",-0.080527,-0.028469,-0.073376,-0.086611,-0.134493,-0.080695,0.033795,8
10,0.958409,0.024407,0.315605,0.018722,1000,sigmoid,"{'C': 1000, 'kernel': 'sigmoid'}",-2.043140,-2.686121,-2.194563,-2.210858,-1.942521,-2.215441,0.255409,18
11,5.440861,0.411034,0.115330,0.073264,1000,linear,"{'C': 1000, 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,1
12,0.985594,0.041915,0.485899,0.009037,2000,rbf,"{'C': 2000, 'kernel': 'rbf'}",-0.143510,-0.087595,-0.113312,-0.128591,-0.193992,-0.133400,0.035492,13
13,1.181671,0.066969,0.129321,0.051569,2000,poly,"{'C': 2000, 'kernel': 'poly'}",-0.020567,0.035685,-0.011468,-0.024587,-0.076360,-0.019459,0.035693,7
14,0.941019,0.046741,0.267836,0.046081,2000,sigmoid,"{'C': 2000, 'kernel': 'sigmoid'}",-7.209317,-9.282940,-7.776578,-7.745074,-6.891719,-7.781126,0.821557,19
15,9.076904,0.799794,0.162579,0.006883,2000,linear,"{'C': 2000, 'kernel': 'linear'}",0.682349,0.630642,0.750714,0.646368,0.722261,0.686467,0.045056,2
16,0.988385,0.027564,0.481882,0.015732,3000,rbf,"{'C': 3000, 'kernel': 'rbf'}",-0.128958,-0.075578,-0.100199,-0.116051,-0.179304,-0.120018,0.034578,11
17,1.430999,0.106985,0.161301,0.014939,3000,poly,"{'C': 3000, 'kernel': 'poly'}",0.037700,0.098496,0.049291,0.035615,-0.020924,0.040035,0.038064,5
18,0.915436,0.008574,0.294219,0.012714,3000,sigmoid,"{'C': 3000, 'kernel': 'sigmoid'}",-15.561853,-20.498908,-17.095474,-16.750877,-15.012168,-16.983856,1.914783,20
19,16.861570,3.588935,0.101739,0.061028,3000,linear,"{'C': 3000, 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,3

In [13]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("children:"))
sex_male_input=int(input("Sex male 0 or 1:"))
smoker_yes_input=int(input("Smoker yes or no:"))

Age:19
BMI:27.900
children:0
Sex male 0 or 1:0
Smoker yes or no:1

In [14]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[25958.05240717]

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  "X does not have valid feature names, but"