In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
independent=dataset[['age', 'bmi', 'children', 'sex_male','smoker_yes']]
dependent=dataset[['charges']]

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['mse','mae','friedman_mse'],
           'max_features':['auto','sqrt','log2'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\tree\_classes.py:370: FutureWarning: Criterion 'mae' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='absolute_error'` which is equivalent.
  FutureWarning,

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [7]:
re=grid.cv_results_
print("The R Score value for the best Parameter{}:".format(grid.best_params_))

The R Score value for the best Parameter{'criterion': 'mae', 'max_features': 'auto', 'splitter': 'random'}:

In [8]:
table=pd.DataFrame.from_dict(re)

In [9]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,7.349772,5.822766,0.000000,0.000000,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.714666,0.651892,0.721364,0.720889,0.681483,0.698059,0.027373,7
1,0.253117,0.020729,0.006250,0.007655,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.733933,0.641793,0.729251,0.692959,0.730931,0.705774,0.035312,4
2,0.243742,0.012500,0.006250,0.007655,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.708847,0.634794,0.627551,0.656044,0.664628,0.658373,0.028629,12
3,0.246867,0.018221,0.003125,0.006250,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.626900,0.590937,0.673558,0.629639,0.651799,0.634567,0.027582,17
4,0.237494,0.011693,0.000000,0.000000,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.739625,0.354592,0.734154,0.743746,0.740638,0.662551,0.154011,11
5,0.243742,0.021194,0.000000,0.000000,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.697753,0.590186,0.634118,0.587138,0.668138,0.635466,0.043208,15
6,0.428112,0.027244,0.009375,0.007655,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.725423,0.597830,0.730561,0.728653,0.753351,0.707164,0.055551,2
7,4.477987,8.338913,0.024999,0.049998,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.733488,0.680912,0.745205,0.725887,0.675955,0.712289,0.028364,1
8,0.259367,0.012500,0.009375,0.007655,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.639980,0.537887,0.737283,0.716514,0.761281,0.678589,0.081251,9
9,0.274992,0.018749,0.024999,0.049998,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.706629,0.555997,0.639507,0.741961,0.644350,0.657689,0.063791,13
10,0.274992,0.007655,0.003125,0.006250,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.680783,0.572547,0.721813,0.725671,0.623697,0.664902,0.059010,10
11,0.256241,0.023382,0.006250,0.007654,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.652136,0.611915,0.634970,0.709592,0.566970,0.635117,0.046944,16
12,0.006250,0.007655,0.009375,0.007655,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.726866,0.639287,0.739893,0.741696,0.681147,0.705778,0.039815,3
13,0.006250,0.007655,0.009375,0.007655,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.648919,0.601151,0.724985,0.732309,0.746370,0.690747,0.056162,8
14,0.006250,0.007655,0.012500,0.006250,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.715977,0.622381,0.693579,0.749072,0.740645,0.704331,0.045360,5
15,0.012500,0.006250,0.006250,0.007655,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.712807,0.637050,0.642021,0.564493,0.599471,0.631168,0.049533,18
16,0.009376,0.007655,0.006250,0.007655,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.719968,0.595201,0.735352,0.735296,0.722142,0.701592,0.053581,6
17,0.012501,0.006250,0.003125,0.006251,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.679746,0.534687,0.637882,0.646391,0.725841,0.644909,0.063189,14

In [10]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("children"))
sex_male_input=int(input("Sex male 0 or 1:"))
smoker_yes_input=int(input("Smoker yes or no:"))

Age:19
BMI:27.900
children0
Sex male 0 or 1:0
Smoker yes or no:1

In [11]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[16884.924]

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  "X does not have valid feature names, but"

In [12]:
import pickle
filename="finalized_Model.sav"
pickle.dump(grid,open(filename,'wb'))

In [13]:
loaded_model=pickle.load(open("finalized_Model.sav",'rb'))
result=loaded_model.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  "X does not have valid feature names, but"

In [14]:
result

array([16884.924])